openapi: "3.0.3"
info:
  title: "Presupuestador"
  version: "1.0.0"
  description: "Un sistema de registro de movimientos con categorías para presupuestar"
servers:
  - url: http://localhost.com:8500/api
paths:
  /entries:
    get:
      summary: "Ver lista de movimientos"
      tags:
        - Movimientos
      responses: 
        200:
          description: "AA"
          content:
            application/json:
              schema:
                type: "array"
                items: 
                  $ref: "#/components/schemas/Entry"
        500:
          description: "Error"
    delete:
      summary: "Borrar todos los movimientos"
      tags:
        - Movimientos
      responses: 
        200:
          description: "Borrado exitoso"
        500:
          description: "Error al borrar"
  /entry:
    post:
      summary: "Agregar nuevo movimiento"
      tags:
        - Movimientos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entry'
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entry'
        400:
          description: "Campos faltantes"
        500:
          description: "Error"
  /entry/{id}:
    delete:
      summary: "Borrar movimiento"
      tags:
        - Movimientos
      parameters:
        - in: path 
          name: "id"
          schema: 
            type: "integer"
          required: true
          description: "Id de movimiento a borrar"          
      responses: 
        200:
          description: "OK"
        400:
          description: "Error al borrar ID"
        500:
          description: "Error"
    put:
      summary: "Modificar Movimiento"
      tags:
        - Movimientos
      parameters:
        - in: path 
          name: "id"
          schema: 
            type: "integer"
          required: true
          description: "Id de movimiento a modificar"     
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entry'
      responses:
        200:
          description: "OK"
          content: 
            application/json:
              schema:
                type: "object" 
                $ref: '#/components/schemas/Entry'
        400:
          description: "Error al actualizar el ID"  
        500:
          description: "Error"



  /budget/:
      get:
        summary: "Acceso a lista de categorías"
        tags:
          - Presupuesto
        responses: 
          200:
            description: "OK"
            content:
              application/json:
                schema:
                  type: "array"
                  items: 
                    $ref: "#/components/schemas/Budget"
          500:
            description: "Error"
      post:
        summary: "Agregar nueva categoría"
        tags:
          - Presupuesto
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Budget'
        responses:
          200:
            description: "OK"
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Budget'
          400: 
            description: "Falta parámetro"
          500:
            description: "Error"
      delete:
        summary: "Borrar todas las categorías"
        tags:
          - Presupuesto
        responses: 
          200:
            description: "OK"
          500:
            description: "Error"
  /budget/{id}:
    delete:
      summary: "Borrar categoría"
      tags:
        - Presupuesto
      parameters:
      - in: path 
        name: "id"
        schema: 
          type: "integer"
        required: true
        description: "Id de línea a borrar"
      responses: 
        200:
          description: "OK"
        400:
          description: "Error al borrar el ID"
        500:
          description: "Error"



      
components:
  schemas:
    Entry:
      type: "object"
      required:
        - date
        - category
        - description
        - amount
        - kind
      properties:
        date:
          type: "string"
          format: "date"
          example: "01-05-2021"
        category:
          type: "string"
          example: "Mercado"
        description:
          type: "string"
          example: "Compra mensual de congelados"
        amount:
          type: "number"
          example: 1000         
        kind:
          type: "string"
          enum: 
          - "Egreso"
          - "Ingreso"



    Budget:
      type: "object"
      required:
        - category
        - description
        - limit
      properties:
        category:
          type: "string"
          example: "Mercado"         
        description:
          type: "string"
          example: "Los gastos realizados en compras de mercado"         
        limit:
          type: "number"
          example: 10000         
            
  